In [ ]:
print ('hi')

hi


In [ ]:
import numpy as np
n=np.zeros(10)
n

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
n=np.ones(10)
n

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
n=np.full(5,10)
n

array([10, 10, 10, 10, 10])

In [ ]:
m=np.arange(9).reshape(3, 3)
m

In [ ]:
m=np.arange(10,50)
m

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
m=np.arange(10,50,2)
m

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [ ]:
m=np.arange(9).reshape(3, 3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
n=np.eye(3)
n

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
m=np.random.random((3,3))
m

array([[0.10347624, 0.98292171, 0.99464121],
       [0.01037736, 0.60838411, 0.26727706],
       [0.6730718 , 0.57088903, 0.5303654 ]])

In [ ]:
m=np.random.normal(size=25)
m

array([-0.8089563 , -1.04307227, -0.12200547,  1.24273832, -0.90238475,
        0.43160667, -1.77400009, -0.17612756, -0.70768948, -1.90110906,
        1.09825193,  1.52071569,  0.86532606, -1.95141742, -0.74169318,
        0.6672819 , -0.03145667, -0.5439114 ,  0.42300032, -0.44735636,
       -0.76442824,  1.33636298,  0.03760331, -1.10630548, -0.64613764])

In [ ]:
m=np.arange(0.01,1,0.01)
m

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])

In [ ]:
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)
print('==========')
print(mat[2:5,1:6])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
print(mat[3][4])

20


In [ ]:
print(mat[0:3,1:2])

[[ 2]
 [ 7]
 [12]]


In [ ]:
print(mat[4:])

[[21 22 23 24 25]]


In [ ]:
print(mat[3:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
print(mat.sum())

325


In [ ]:
print(mat.std())

7.211102550927978


In [ ]:
print(mat.sum(axis=0))

[55 60 65 70 75]
